# **Array**



In [30]:
''' 
it can contain data of limited types only, not multiple
it is of fixed length in other languages except python
'b' : signed integer
'B' :unsigned integer
'u': unicode integer
'f': floating point
'd': floating points
Basically capital means signed, and small means unsigned'''

from array import *
a = array('b',[25,24,10,45,65])
print(type(a))
for i in a:
    print(i)

print()
for i in range(0,5):
    print(a[i], end = " ")

print()

i = 0
while(i<len(a)):
    print(a[i])
    i+=1
   
print()

a.append(70)
for i in range(0,6):
    print(a[i], end =' ')

print()
print("Count of 70 is", a.count(70))

print("Index of 10 is", a.index(10))

#Pop deletes and returns the last element aor we can menntion the index of element to be deleted
a.pop()

a.pop(1)
print()

for i in range(0,4):
    print(a[i])

#remove() removes specfic value
a.remove(10)
for i in range(0,3):
    print(a[i], end =' ')

print()
a.reverse()
for i in range(0,3):
    print(a[i], end = ' ')

print()
#tolist() converts array into list
b = a.tolist()
print(b)





<class 'array.array'>
25
24
10
45
65

25 24 10 45 65 
25
24
10
45
65

25 24 10 45 65 70 
Count of 70 is 1
Index of 10 is 2

25
10
45
65
25 45 65 
65 45 25 
[65, 45, 25]


# **List**

In [64]:
'''
List is a class
List is a collection of heterogenous elements
List is mutable
List elements are indexed
List is an iterable
List can grow(dynamic array)
List can contain different type elements'''

#fromlist() converts list to array
#append()
#clear()
#count()
#extend
#index()
#pop()
#sort()
#remove()
#reverse

l = [3,5,5,6,'Namir']
print(l)

for i in range(0,4):
    print(l[i],end = ' ')

print()
l.append('Shah')
print(l)

l.count(5)
print()

l.index(6)

l.reverse()

x = [4,5,16,20,6,10,12]
print(len(x))

print(max(x))

print(sum(x))

print(sorted(x))

print(sorted(x, reverse = True))






[3, 5, 5, 6, 'Namir']
3 5 5 6 
[3, 5, 5, 6, 'Namir', 'Shah']

7
20
73
[4, 5, 6, 10, 12, 16, 20]
[20, 16, 12, 10, 6, 5, 4]


# **Numpy**


In [75]:
import numpy as np
x = np.array([1,2,5,6,10,1,28])
print(x)

for i in range(0,7):
    print(x[i],end =' ')

print()
#2D array
a = np.array([[1,2,3],[4,5,6]])
print(a)


[ 1  2  5  6 10  1 28]
1 2 5 6 10 1 28 
[[1 2 3]
 [4 5 6]]


# **Classes and Object**

Class: it is the description of an object, it defines various attributes of an object



Encapsulation: An act of combining properties and methods related to same object is known as encapsulation, class is a way to implement encapsulation

Atributes: they are member variales and member functions

In [ ]:
class Test:
    x = 10
    def maths():
        #some code

#Here x and maths() are attributus

Object: it is an instance of a class. in python 2 types: class object, instance object

In [4]:
#Instance object
class Test:
    x = 100
    def marks(self):
        print("Marks are", self.x)

t1 = Test()  #variables inside instance object are called instance object variable, initially when created instance objects are empty
t1.marks()

Marks are 100


In [ ]:
#class object: one class has exactly only one class object
class Animal:
    x = "Tiger"          #variables inside class object are called class object variables or static variables
    print("Name is",x)

#Here Animal is the class object


__init__() method: it is like constructor

In [1]:
class Animal:
    def __init__(self):
        self.a = 10   #instance object variable
        self.b = 20   #instance object variable

a1 = Animal()    #__init__(a1)
print(a1.a)
print(a1.b)

10
20


In [3]:
class Bird:
    def __init__(self,x,y):
        self.a = 10
        self.x = x
        self.y = y

t1 =Bird(20,30)
print(t1.a, t1.x,t1.y)

10 20 30


Methods

In [28]:
#Instance method: this should have atleast 1 parameter in the functions, it does instance object specific task
class Test:
    def maths(self):
        return "10"

t1 = Test()
print(t1.maths())

class Game:
    def name(self,x):
        self.x = x
        print("Name of game is",self.x)

g1 = Game()
g1.name("GOW")



10
Name of game is GOW


In [25]:
#static method: the user has the choice of keeping the parameter in the function
class Test:
    @staticmethod
    def english():
        return "Hello, I am a static method in the class Test"

t1 = Test()
print(t1.english())

Hello, I am a static method in the class Test


In [29]:
#class method: they are used for classs object variable
class Animal:
    x = 100
    @classmethod
    def weight(cls):
        print("The weight of Animal is",cls.x,"kg")

Animal.weight()


The weight of Animal is 100 kg


In [32]:
class Employee:
    def __init__(self,name=None,empid=None,salary=None):
        self.name = name
        self.empid = empid
        self.salary = salary
    def setName(self,name):
        self.name = name
    def setEmpid(self,empid):
        self.empid = empid
    def setSalary(self,salary):
        self.salary = salary
    def getName(self):
        return self.name
    def getEmpid(self):
        return self.empid
    def getSalary(self):
        return self.salary
    
e1 = Employee()
e2 = Employee("DR",167,150000)
e1.setName("FR")
e1.setEmpid(165)
e1.setSalary(250000)
print(e1.getName(),e1.getEmpid(),e1.getSalary())
print(e2.getName(),e2.getEmpid(),e2.getSalary())

FR 165 250000
DR 167 150000


# **Linked List**

In [ ]:
#Creating a Node
class Node:
    def __init__(self,item = None, next = None):
        self.item = item
        self.next = next

# **Singly Linked List**

SLL is a linear data structure, it can grow and shrink, it can contain only on reference variable which points to the next node

In [7]:
class Node:
    def __init__(self,item = None, next = None):
        self.item = item
        self.next = next

class SLL:
    def __init__(self,start = None):
        self.start = start   #consider this reference variable 
    def isEmpty(self):
        return self.start == None
    def insert_at_start(self,data):
        n = Node(data, self.start)    #inserting a node with data and coppying the value of start which points to the next node in list
        self.start = n # now the start node is replaced/said to be n which will have the data as well as reference variable which will point to next node in the list
    def insert_at_end(self,data):
        n= Node(data) #not assigning self.next since last node wont be refering to next node so it is default None
        if not self.isEmpty():
            temp = self.start
            while temp.next is not None:
                temp = temp.next
            temp.next = n
        else:
            self.start = n       
    def search(self,data):
        temp = self.start
        while self.start is not None:    #traversing till self.start is not empty
            if temp.item == data:
                return temp
            temp = temp.next
        return None
    def insert_after(self,temp,data):
        if temp is not None:
            n = Node(data,temp.next)
            temp.next = n
    def print_list(self):
        temp = self.start
        while temp is not None:
            print(temp.item,end='->')
            temp = temp.next
        print("None")


#Driver Code
l1 = SLL()
l1.insert_at_start(10)
l1.insert_after(l1.search(10),20)
l1.insert_after(l1.search(20),30)
l1.insert_after(l1.search(30),40)
l1.insert_after(l1.search(20),25)
l1.insert_at_end(50)
l1.print_list()
            
                

10->20->20->30->50->None
